//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyTitle("Consumentor.Shopgun")]
[assembly: AssemblyCompany("Consumentor Ek. Förening")]
[assembly: AssemblyProduct("Consumentor.Shopgun")]
[assembly: AssemblyCopyright("Copyright © Consumentor Ek. Förening 2010")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]