//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Consumentor.ShopGun.Gateway.org.gs1.gepir {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="routerSoap", Namespace="http://www.gepir.org/")]
    public partial class router : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GepirVersion2OperationCompleted;
        
        private gepirRequestHeader gepirRequestHeaderValueField;
        
        private gepirResponseHeader gepirResponseHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetPartyByGLNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOwnerOfGLNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartyByGTINOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartyBySSCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartyByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemByGTINOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatisticsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SessionAuthorizeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public router() {
            this.Url = global::Consumentor.ShopGun.Gateway.Properties.Settings.Default.Consumentor_ShopGun_Gateway_org_gs1_gepir_router;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public gepirRequestHeader gepirRequestHeaderValue {
            get {
                return this.gepirRequestHeaderValueField;
            }
            set {
                this.gepirRequestHeaderValueField = value;
            }
        }
        
        public gepirResponseHeader gepirResponseHeaderValue {
            get {
                return this.gepirResponseHeaderValueField;
            }
            set {
                this.gepirResponseHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GepirVersion2CompletedEventHandler GepirVersion2Completed;
        
        /// <remarks/>
        public event GetPartyByGLNCompletedEventHandler GetPartyByGLNCompleted;
        
        /// <remarks/>
        public event GetOwnerOfGLNCompletedEventHandler GetOwnerOfGLNCompleted;
        
        /// <remarks/>
        public event GetPartyByGTINCompletedEventHandler GetPartyByGTINCompleted;
        
        /// <remarks/>
        public event GetPartyBySSCCCompletedEventHandler GetPartyBySSCCCompleted;
        
        /// <remarks/>
        public event GetPartyByNameCompletedEventHandler GetPartyByNameCompleted;
        
        /// <remarks/>
        public event GetItemByGTINCompletedEventHandler GetItemByGTINCompleted;
        
        /// <remarks/>
        public event GetStatisticsCompletedEventHandler GetStatisticsCompleted;
        
        /// <remarks/>
        public event GetAuthorizationCompletedEventHandler GetAuthorizationCompleted;
        
        /// <remarks/>
        public event SessionAuthorizeCompletedEventHandler SessionAuthorizeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gepir.ean.ch/GepirVersion2", RequestElementName="GepirVersion2Request", RequestNamespace="http://gepir.ean.ch/Request", ResponseNamespace="http://gepir.ean.ch/Response", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GepirVersion2() {
            object[] results = this.Invoke("GepirVersion2", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GepirVersion2Async() {
            this.GepirVersion2Async(null);
        }
        
        /// <remarks/>
        public void GepirVersion2Async(object userState) {
            if ((this.GepirVersion2OperationCompleted == null)) {
                this.GepirVersion2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGepirVersion2OperationCompleted);
            }
            this.InvokeAsync("GepirVersion2", new object[0], this.GepirVersion2OperationCompleted, userState);
        }
        
        private void OnGepirVersion2OperationCompleted(object arg) {
            if ((this.GepirVersion2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GepirVersion2Completed(this, new GepirVersion2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetPartyByGLN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirParty", Namespace="http://www.gepir.org/")]
        public gepirParty GetPartyByGLN([System.Xml.Serialization.XmlElementAttribute("GetPartyByGLN", Namespace="http://www.gepir.org/")] GetPartyByGLN GetPartyByGLN1) {
            object[] results = this.Invoke("GetPartyByGLN", new object[] {
                        GetPartyByGLN1});
            return ((gepirParty)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartyByGLNAsync(GetPartyByGLN GetPartyByGLN1) {
            this.GetPartyByGLNAsync(GetPartyByGLN1, null);
        }
        
        /// <remarks/>
        public void GetPartyByGLNAsync(GetPartyByGLN GetPartyByGLN1, object userState) {
            if ((this.GetPartyByGLNOperationCompleted == null)) {
                this.GetPartyByGLNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartyByGLNOperationCompleted);
            }
            this.InvokeAsync("GetPartyByGLN", new object[] {
                        GetPartyByGLN1}, this.GetPartyByGLNOperationCompleted, userState);
        }
        
        private void OnGetPartyByGLNOperationCompleted(object arg) {
            if ((this.GetPartyByGLNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartyByGLNCompleted(this, new GetPartyByGLNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetOwnerOfGLN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirParty", Namespace="http://www.gepir.org/")]
        public gepirParty GetOwnerOfGLN([System.Xml.Serialization.XmlElementAttribute("GetOwnerOfGLN", Namespace="http://www.gepir.org/")] GetOwnerOfGLN GetOwnerOfGLN1) {
            object[] results = this.Invoke("GetOwnerOfGLN", new object[] {
                        GetOwnerOfGLN1});
            return ((gepirParty)(results[0]));
        }
        
        /// <remarks/>
        public void GetOwnerOfGLNAsync(GetOwnerOfGLN GetOwnerOfGLN1) {
            this.GetOwnerOfGLNAsync(GetOwnerOfGLN1, null);
        }
        
        /// <remarks/>
        public void GetOwnerOfGLNAsync(GetOwnerOfGLN GetOwnerOfGLN1, object userState) {
            if ((this.GetOwnerOfGLNOperationCompleted == null)) {
                this.GetOwnerOfGLNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOwnerOfGLNOperationCompleted);
            }
            this.InvokeAsync("GetOwnerOfGLN", new object[] {
                        GetOwnerOfGLN1}, this.GetOwnerOfGLNOperationCompleted, userState);
        }
        
        private void OnGetOwnerOfGLNOperationCompleted(object arg) {
            if ((this.GetOwnerOfGLNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOwnerOfGLNCompleted(this, new GetOwnerOfGLNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetPartyByGTIN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirParty", Namespace="http://www.gepir.org/")]
        public gepirParty GetPartyByGTIN([System.Xml.Serialization.XmlElementAttribute("GetPartyByGTIN", Namespace="http://www.gepir.org/")] GetPartyByGTIN GetPartyByGTIN1) {
            object[] results = this.Invoke("GetPartyByGTIN", new object[] {
                        GetPartyByGTIN1});
            return ((gepirParty)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartyByGTINAsync(GetPartyByGTIN GetPartyByGTIN1) {
            this.GetPartyByGTINAsync(GetPartyByGTIN1, null);
        }
        
        /// <remarks/>
        public void GetPartyByGTINAsync(GetPartyByGTIN GetPartyByGTIN1, object userState) {
            if ((this.GetPartyByGTINOperationCompleted == null)) {
                this.GetPartyByGTINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartyByGTINOperationCompleted);
            }
            this.InvokeAsync("GetPartyByGTIN", new object[] {
                        GetPartyByGTIN1}, this.GetPartyByGTINOperationCompleted, userState);
        }
        
        private void OnGetPartyByGTINOperationCompleted(object arg) {
            if ((this.GetPartyByGTINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartyByGTINCompleted(this, new GetPartyByGTINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetPartyBySSCC", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirParty", Namespace="http://www.gepir.org/")]
        public gepirParty GetPartyBySSCC([System.Xml.Serialization.XmlElementAttribute("GetPartyBySSCC", Namespace="http://www.gepir.org/")] GetPartyBySSCC GetPartyBySSCC1) {
            object[] results = this.Invoke("GetPartyBySSCC", new object[] {
                        GetPartyBySSCC1});
            return ((gepirParty)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartyBySSCCAsync(GetPartyBySSCC GetPartyBySSCC1) {
            this.GetPartyBySSCCAsync(GetPartyBySSCC1, null);
        }
        
        /// <remarks/>
        public void GetPartyBySSCCAsync(GetPartyBySSCC GetPartyBySSCC1, object userState) {
            if ((this.GetPartyBySSCCOperationCompleted == null)) {
                this.GetPartyBySSCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartyBySSCCOperationCompleted);
            }
            this.InvokeAsync("GetPartyBySSCC", new object[] {
                        GetPartyBySSCC1}, this.GetPartyBySSCCOperationCompleted, userState);
        }
        
        private void OnGetPartyBySSCCOperationCompleted(object arg) {
            if ((this.GetPartyBySSCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartyBySSCCCompleted(this, new GetPartyBySSCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetPartyByName", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirParty", Namespace="http://www.gepir.org/")]
        public gepirParty GetPartyByName([System.Xml.Serialization.XmlElementAttribute("GetPartyByName", Namespace="http://www.gepir.org/")] GetPartyByName GetPartyByName1) {
            object[] results = this.Invoke("GetPartyByName", new object[] {
                        GetPartyByName1});
            return ((gepirParty)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartyByNameAsync(GetPartyByName GetPartyByName1) {
            this.GetPartyByNameAsync(GetPartyByName1, null);
        }
        
        /// <remarks/>
        public void GetPartyByNameAsync(GetPartyByName GetPartyByName1, object userState) {
            if ((this.GetPartyByNameOperationCompleted == null)) {
                this.GetPartyByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartyByNameOperationCompleted);
            }
            this.InvokeAsync("GetPartyByName", new object[] {
                        GetPartyByName1}, this.GetPartyByNameOperationCompleted, userState);
        }
        
        private void OnGetPartyByNameOperationCompleted(object arg) {
            if ((this.GetPartyByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartyByNameCompleted(this, new GetPartyByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetItemByGTIN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirItem", Namespace="http://www.gepir.org/")]
        public gepirItem GetItemByGTIN([System.Xml.Serialization.XmlElementAttribute("GetItemByGTIN", Namespace="http://www.gepir.org/")] GetItemByGTIN GetItemByGTIN1) {
            object[] results = this.Invoke("GetItemByGTIN", new object[] {
                        GetItemByGTIN1});
            return ((gepirItem)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemByGTINAsync(GetItemByGTIN GetItemByGTIN1) {
            this.GetItemByGTINAsync(GetItemByGTIN1, null);
        }
        
        /// <remarks/>
        public void GetItemByGTINAsync(GetItemByGTIN GetItemByGTIN1, object userState) {
            if ((this.GetItemByGTINOperationCompleted == null)) {
                this.GetItemByGTINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemByGTINOperationCompleted);
            }
            this.InvokeAsync("GetItemByGTIN", new object[] {
                        GetItemByGTIN1}, this.GetItemByGTINOperationCompleted, userState);
        }
        
        private void OnGetItemByGTINOperationCompleted(object arg) {
            if ((this.GetItemByGTINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemByGTINCompleted(this, new GetItemByGTINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetStatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirStatistics", Namespace="http://www.gepir.org/")]
        public gepirStatistics GetStatistics([System.Xml.Serialization.XmlElementAttribute("GetStatistics", Namespace="http://www.gepir.org/")] GetStatistics GetStatistics1) {
            object[] results = this.Invoke("GetStatistics", new object[] {
                        GetStatistics1});
            return ((gepirStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatisticsAsync(GetStatistics GetStatistics1) {
            this.GetStatisticsAsync(GetStatistics1, null);
        }
        
        /// <remarks/>
        public void GetStatisticsAsync(GetStatistics GetStatistics1, object userState) {
            if ((this.GetStatisticsOperationCompleted == null)) {
                this.GetStatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatisticsOperationCompleted);
            }
            this.InvokeAsync("GetStatistics", new object[] {
                        GetStatistics1}, this.GetStatisticsOperationCompleted, userState);
        }
        
        private void OnGetStatisticsOperationCompleted(object arg) {
            if ((this.GetStatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatisticsCompleted(this, new GetStatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirRequestHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("gepirResponseHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/GetAuthorization", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("gepirAuthorization", Namespace="http://www.gepir.org/")]
        public gepirAuthorization GetAuthorization([System.Xml.Serialization.XmlElementAttribute("GetAuthorization", Namespace="http://www.gepir.org/")] GetAuthorization GetAuthorization1) {
            object[] results = this.Invoke("GetAuthorization", new object[] {
                        GetAuthorization1});
            return ((gepirAuthorization)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizationAsync(GetAuthorization GetAuthorization1) {
            this.GetAuthorizationAsync(GetAuthorization1, null);
        }
        
        /// <remarks/>
        public void GetAuthorizationAsync(GetAuthorization GetAuthorization1, object userState) {
            if ((this.GetAuthorizationOperationCompleted == null)) {
                this.GetAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationOperationCompleted);
            }
            this.InvokeAsync("GetAuthorization", new object[] {
                        GetAuthorization1}, this.GetAuthorizationOperationCompleted, userState);
        }
        
        private void OnGetAuthorizationOperationCompleted(object arg) {
            if ((this.GetAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizationCompleted(this, new GetAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.gepir.org/SessionAuthorize", RequestNamespace="http://www.gepir.org/", ResponseNamespace="http://www.gepir.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SessionAuthorize() {
            this.Invoke("SessionAuthorize", new object[0]);
        }
        
        /// <remarks/>
        public void SessionAuthorizeAsync() {
            this.SessionAuthorizeAsync(null);
        }
        
        /// <remarks/>
        public void SessionAuthorizeAsync(object userState) {
            if ((this.SessionAuthorizeOperationCompleted == null)) {
                this.SessionAuthorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSessionAuthorizeOperationCompleted);
            }
            this.InvokeAsync("SessionAuthorize", new object[0], this.SessionAuthorizeOperationCompleted, userState);
        }
        
        private void OnSessionAuthorizeOperationCompleted(object arg) {
            if ((this.SessionAuthorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SessionAuthorizeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gepir.org/", IsNullable=false)]
    public partial class gepirRequestHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string requesterGlnField;
        
        private int cascadeField;
        
        private bool cascadeFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string requesterGln {
            get {
                return this.requesterGlnField;
            }
            set {
                this.requesterGlnField = value;
            }
        }
        
        /// <remarks/>
        public int cascade {
            get {
                return this.cascadeField;
            }
            set {
                this.cascadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cascadeSpecified {
            get {
                return this.cascadeFieldSpecified;
            }
            set {
                this.cascadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirAuthorization {
        
        private string glnField;
        
        private string ipField;
        
        private string partyNameField;
        
        private string authorization_levelField;
        
        private System.DateTime addedField;
        
        private System.DateTime updatedField;
        
        private decimal versionField;
        
        public gepirAuthorization() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        public string gln {
            get {
                return this.glnField;
            }
            set {
                this.glnField = value;
            }
        }
        
        /// <remarks/>
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string partyName {
            get {
                return this.partyNameField;
            }
            set {
                this.partyNameField = value;
            }
        }
        
        /// <remarks/>
        public string authorization_level {
            get {
                return this.authorization_levelField;
            }
            set {
                this.authorization_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime added {
            get {
                return this.addedField;
            }
            set {
                this.addedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetAuthorization {
        
        private string requestedGlnField;
        
        private string requestedIpField;
        
        private decimal versionField;
        
        public GetAuthorization() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        public string requestedGln {
            get {
                return this.requestedGlnField;
            }
            set {
                this.requestedGlnField = value;
            }
        }
        
        /// <remarks/>
        public string requestedIp {
            get {
                return this.requestedIpField;
            }
            set {
                this.requestedIpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatisticsLineCountHitsHits {
        
        private string requesterGlnField;
        
        private string hitCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string requesterGln {
            get {
                return this.requesterGlnField;
            }
            set {
                this.requesterGlnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string HitCount {
            get {
                return this.hitCountField;
            }
            set {
                this.hitCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatisticsLineCountHits {
        
        private gepirStatisticsLineCountHitsHits[] hitsField;
        
        private gepirStatisticsLineCountHitsMethod methodField;
        
        private bool methodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hits")]
        public gepirStatisticsLineCountHitsHits[] Hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public gepirStatisticsLineCountHitsMethod Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MethodSpecified {
            get {
                return this.methodFieldSpecified;
            }
            set {
                this.methodFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum gepirStatisticsLineCountHitsMethod {
        
        /// <remarks/>
        GetItemByGTIN,
        
        /// <remarks/>
        GetOwnerOfGLN,
        
        /// <remarks/>
        GetPartyByGLN,
        
        /// <remarks/>
        GetPartyByGTIN,
        
        /// <remarks/>
        GetPartyByName,
        
        /// <remarks/>
        GetPartyBySSCC,
        
        /// <remarks/>
        GetStatistics,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatisticsLineCountersCountClient {
        
        private string iPAddressField;
        
        private string hitCountField;
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string HitCount {
            get {
                return this.hitCountField;
            }
            set {
                this.hitCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatisticsLineCounters {
        
        private string countGCPField;
        
        private string countGLNField;
        
        private string countGTINField;
        
        private gepirStatisticsLineCountersCountClient[] countClientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string CountGCP {
            get {
                return this.countGCPField;
            }
            set {
                this.countGCPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string CountGLN {
            get {
                return this.countGLNField;
            }
            set {
                this.countGLNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string CountGTIN {
            get {
                return this.countGTINField;
            }
            set {
                this.countGTINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountClient")]
        public gepirStatisticsLineCountersCountClient[] CountClient {
            get {
                return this.countClientField;
            }
            set {
                this.countClientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatisticsLine {
        
        private string countryISOCodeField;
        
        private gepirStatisticsLineCounters countersField;
        
        private gepirStatisticsLineCountHits[] countHitsField;
        
        /// <remarks/>
        public string countryISOCode {
            get {
                return this.countryISOCodeField;
            }
            set {
                this.countryISOCodeField = value;
            }
        }
        
        /// <remarks/>
        public gepirStatisticsLineCounters Counters {
            get {
                return this.countersField;
            }
            set {
                this.countersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountHits")]
        public gepirStatisticsLineCountHits[] CountHits {
            get {
                return this.countHitsField;
            }
            set {
                this.countHitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirStatistics {
        
        private System.DateTime periodBeginField;
        
        private System.DateTime periodEndField;
        
        private gepirStatisticsLine[] statisticsLineField;
        
        private decimal versionField;
        
        public gepirStatistics() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime periodBegin {
            get {
                return this.periodBeginField;
            }
            set {
                this.periodBeginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime periodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statisticsLine")]
        public gepirStatisticsLine[] statisticsLine {
            get {
                return this.statisticsLineField;
            }
            set {
                this.statisticsLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetStatistics {
        
        private string requestedCountryField;
        
        private System.DateTime periodBeginField;
        
        private System.DateTime periodEndField;
        
        private decimal versionField;
        
        public GetStatistics() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        public string requestedCountry {
            get {
                return this.requestedCountryField;
            }
            set {
                this.requestedCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime periodBegin {
            get {
                return this.periodBeginField;
            }
            set {
                this.periodBeginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime periodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class itemDataLineTypeChildItemsChildItem {
        
        private string gtinField;
        
        private string numberContainedField;
        
        /// <remarks/>
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string numberContained {
            get {
                return this.numberContainedField;
            }
            set {
                this.numberContainedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class classificationCodeType {
        
        private classificationCodeTypeClassificationSystemCode classificationSystemCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public classificationCodeTypeClassificationSystemCode classificationSystemCode {
            get {
                return this.classificationSystemCodeField;
            }
            set {
                this.classificationSystemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum classificationCodeTypeClassificationSystemCode {
        
        /// <remarks/>
        UNSPSC,
        
        /// <remarks/>
        ISIC,
        
        /// <remarks/>
        GPC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class itemDataLineTypeLinkUri {
        
        private itemDataLineTypeLinkUriFormat formatField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public itemDataLineTypeLinkUriFormat format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum itemDataLineTypeLinkUriFormat {
        
        /// <remarks/>
        html,
        
        /// <remarks/>
        xml,
        
        /// <remarks/>
        text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class itemDataLineTypeNetContent {
        
        private uomType uomField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uomType uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum uomType {
        
        /// <remarks/>
        PCE,
        
        /// <remarks/>
        GRM,
        
        /// <remarks/>
        KGM,
        
        /// <remarks/>
        LBS,
        
        /// <remarks/>
        MLT,
        
        /// <remarks/>
        LTR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class itemDataLineType {
        
        private string gtinField;
        
        private string informationProviderGlnField;
        
        private string manufacturerGlnField;
        
        private string itemNameField;
        
        private string brandNameField;
        
        private itemDataLineTypeTradeItemUnitDescriptor tradeItemUnitDescriptorField;
        
        private string descriptiveSizeField;
        
        private itemDataLineTypeNetContent netContentField;
        
        private itemDataLineTypeLinkUri[] linkUriField;
        
        private classificationCodeType[] classificationCodeField;
        
        private System.DateTime lastChangeDateTimeField;
        
        private bool lastChangeDateTimeFieldSpecified;
        
        private itemDataLineTypeChildItemsChildItem[] childItemsField;
        
        private string langField;
        
        public itemDataLineType() {
            this.langField = "en";
        }
        
        /// <remarks/>
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        public string informationProviderGln {
            get {
                return this.informationProviderGlnField;
            }
            set {
                this.informationProviderGlnField = value;
            }
        }
        
        /// <remarks/>
        public string manufacturerGln {
            get {
                return this.manufacturerGlnField;
            }
            set {
                this.manufacturerGlnField = value;
            }
        }
        
        /// <remarks/>
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string brandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
            }
        }
        
        /// <remarks/>
        public itemDataLineTypeTradeItemUnitDescriptor tradeItemUnitDescriptor {
            get {
                return this.tradeItemUnitDescriptorField;
            }
            set {
                this.tradeItemUnitDescriptorField = value;
            }
        }
        
        /// <remarks/>
        public string descriptiveSize {
            get {
                return this.descriptiveSizeField;
            }
            set {
                this.descriptiveSizeField = value;
            }
        }
        
        /// <remarks/>
        public itemDataLineTypeNetContent netContent {
            get {
                return this.netContentField;
            }
            set {
                this.netContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("linkUri")]
        public itemDataLineTypeLinkUri[] linkUri {
            get {
                return this.linkUriField;
            }
            set {
                this.linkUriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classificationCode")]
        public classificationCodeType[] classificationCode {
            get {
                return this.classificationCodeField;
            }
            set {
                this.classificationCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastChangeDateTime {
            get {
                return this.lastChangeDateTimeField;
            }
            set {
                this.lastChangeDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastChangeDateTimeSpecified {
            get {
                return this.lastChangeDateTimeFieldSpecified;
            }
            set {
                this.lastChangeDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("childItem", IsNullable=false)]
        public itemDataLineTypeChildItemsChildItem[] childItems {
            get {
                return this.childItemsField;
            }
            set {
                this.childItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum itemDataLineTypeTradeItemUnitDescriptor {
        
        /// <remarks/>
        BASE_UNIT_OR_EACH,
        
        /// <remarks/>
        PACK_OR_INNER_PACK,
        
        /// <remarks/>
        CASE,
        
        /// <remarks/>
        DISPLAY_SHIPPER,
        
        /// <remarks/>
        PALLET,
        
        /// <remarks/>
        MIXED_MODULE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirItem {
        
        private itemDataLineType[] itemDataLineField;
        
        private decimal versionField;
        
        public gepirItem() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemDataLine")]
        public itemDataLineType[] itemDataLine {
            get {
                return this.itemDataLineField;
            }
            set {
                this.itemDataLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetItemByGTIN {
        
        private string requestedGtinField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        public GetItemByGTIN() {
            this.versionField = ((decimal)(3.10m));
        }
        
        /// <remarks/>
        public string requestedGtin {
            get {
                return this.requestedGtinField;
            }
            set {
                this.requestedGtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetPartyByName {
        
        private string requestedPartyNameField;
        
        private string requestedStreetAddressField;
        
        private string requestedPostalCodeField;
        
        private string requestedCityField;
        
        private string requestedCountryField;
        
        private string[] requestedKeywordsField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        /// <remarks/>
        public string requestedPartyName {
            get {
                return this.requestedPartyNameField;
            }
            set {
                this.requestedPartyNameField = value;
            }
        }
        
        /// <remarks/>
        public string requestedStreetAddress {
            get {
                return this.requestedStreetAddressField;
            }
            set {
                this.requestedStreetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string requestedPostalCode {
            get {
                return this.requestedPostalCodeField;
            }
            set {
                this.requestedPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string requestedCity {
            get {
                return this.requestedCityField;
            }
            set {
                this.requestedCityField = value;
            }
        }
        
        /// <remarks/>
        public string requestedCountry {
            get {
                return this.requestedCountryField;
            }
            set {
                this.requestedCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("keyword", IsNullable=false)]
        public string[] requestedKeywords {
            get {
                return this.requestedKeywordsField;
            }
            set {
                this.requestedKeywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetPartyBySSCC {
        
        private string requestedSsccField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        /// <remarks/>
        public string requestedSscc {
            get {
                return this.requestedSsccField;
            }
            set {
                this.requestedSsccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetPartyByGTIN {
        
        private string[] requestedGtinField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestedGtin")]
        public string[] requestedGtin {
            get {
                return this.requestedGtinField;
            }
            set {
                this.requestedGtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetOwnerOfGLN {
        
        private string requestedGlnField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        /// <remarks/>
        public string requestedGln {
            get {
                return this.requestedGlnField;
            }
            set {
                this.requestedGlnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class partyChildType {
        
        private partyRoleListType[] partyChildRoleField;
        
        private string glnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partyChildRole")]
        public partyRoleListType[] partyChildRole {
            get {
                return this.partyChildRoleField;
            }
            set {
                this.partyChildRoleField = value;
            }
        }
        
        /// <remarks/>
        public string gln {
            get {
                return this.glnField;
            }
            set {
                this.glnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum partyRoleListType {
        
        /// <remarks/>
        BILL_TO,
        
        /// <remarks/>
        BUYER,
        
        /// <remarks/>
        CONSUMER,
        
        /// <remarks/>
        CORPORATE_IDENTITY,
        
        /// <remarks/>
        DELIVERY_PARTY,
        
        /// <remarks/>
        DISTRIBUTOR_AND_OR_BROKER,
        
        /// <remarks/>
        INFORMATION_PROVIDER,
        
        /// <remarks/>
        INVOICEE,
        
        /// <remarks/>
        ISSUER_OF_INVOICE,
        
        /// <remarks/>
        LOGISTICS_SERVICE_PROVIDER,
        
        /// <remarks/>
        MANUFACTURING_PLANT,
        
        /// <remarks/>
        MARK_FOR,
        
        /// <remarks/>
        MESSAGE_FROM,
        
        /// <remarks/>
        MESSAGE_RECIPIENT,
        
        /// <remarks/>
        OPERATOR,
        
        /// <remarks/>
        PARTY_TO_RECEIVE_COMMERCIAL_INVOICE,
        
        /// <remarks/>
        PAYEE,
        
        /// <remarks/>
        PAYER,
        
        /// <remarks/>
        SELLER,
        
        /// <remarks/>
        SHIP_FROM,
        
        /// <remarks/>
        SHIP_TO,
        
        /// <remarks/>
        STORE,
        
        /// <remarks/>
        SUPPLIER,
        
        /// <remarks/>
        WAREHOUSE_AND_OR_DEPOT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class CommunicationChannelType {
        
        private CommunicationChannelCodeType communicationChannelCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CommunicationChannelCodeType communicationChannelCode {
            get {
                return this.communicationChannelCodeField;
            }
            set {
                this.communicationChannelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public enum CommunicationChannelCodeType {
        
        /// <remarks/>
        TELEPHONE,
        
        /// <remarks/>
        TELEFAX,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        WEBSITE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class partyContactType {
        
        private string contactNameField;
        
        private CommunicationChannelType[] communicationChannelField;
        
        /// <remarks/>
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("communicationChannel")]
        public CommunicationChannelType[] communicationChannel {
            get {
                return this.communicationChannelField;
            }
            set {
                this.communicationChannelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class partyDataLineType {
        
        private string glnField;
        
        private string returnCodeField;
        
        private string informationProviderGlnField;
        
        private System.DateTime lastChangeDateTimeField;
        
        private bool lastChangeDateTimeFieldSpecified;
        
        private string gcpField;
        
        private string[] additionalPartyIdField;
        
        private string partyNameField;
        
        private string[] streetAddressField;
        
        private string pOBoxNumberField;
        
        private string subDivisionField;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string countryISOCodeField;
        
        private partyContactType[] contactField;
        
        private partyRoleListType partyRoleField;
        
        private bool partyRoleFieldSpecified;
        
        private partyChildType[] partyContainmentField;
        
        private string langField;
        
        /// <remarks/>
        public string gln {
            get {
                return this.glnField;
            }
            set {
                this.glnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string informationProviderGln {
            get {
                return this.informationProviderGlnField;
            }
            set {
                this.informationProviderGlnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastChangeDateTime {
            get {
                return this.lastChangeDateTimeField;
            }
            set {
                this.lastChangeDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastChangeDateTimeSpecified {
            get {
                return this.lastChangeDateTimeFieldSpecified;
            }
            set {
                this.lastChangeDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string gcp {
            get {
                return this.gcpField;
            }
            set {
                this.gcpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalPartyId")]
        public string[] additionalPartyId {
            get {
                return this.additionalPartyIdField;
            }
            set {
                this.additionalPartyIdField = value;
            }
        }
        
        /// <remarks/>
        public string partyName {
            get {
                return this.partyNameField;
            }
            set {
                this.partyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("streetAddress")]
        public string[] streetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string pOBoxNumber {
            get {
                return this.pOBoxNumberField;
            }
            set {
                this.pOBoxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string subDivision {
            get {
                return this.subDivisionField;
            }
            set {
                this.subDivisionField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string countryISOCode {
            get {
                return this.countryISOCodeField;
            }
            set {
                this.countryISOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contact")]
        public partyContactType[] contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public partyRoleListType partyRole {
            get {
                return this.partyRoleField;
            }
            set {
                this.partyRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partyRoleSpecified {
            get {
                return this.partyRoleFieldSpecified;
            }
            set {
                this.partyRoleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("partyChild", IsNullable=false)]
        public partyChildType[] partyContainment {
            get {
                return this.partyContainmentField;
            }
            set {
                this.partyContainmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class gepirParty {
        
        private partyDataLineType[] partyDataLineField;
        
        private decimal versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partyDataLine")]
        public partyDataLineType[] partyDataLine {
            get {
                return this.partyDataLineField;
            }
            set {
                this.partyDataLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    public partial class GetPartyByGLN {
        
        private string[] requestedGlnField;
        
        private string[] requestedLanguagesField;
        
        private decimal versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestedGln")]
        public string[] requestedGln {
            get {
                return this.requestedGlnField;
            }
            set {
                this.requestedGlnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="language", IsNullable=false)]
        public string[] requestedLanguages {
            get {
                return this.requestedLanguagesField;
            }
            set {
                this.requestedLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gepir.org/", IsNullable=false)]
    public partial class gepirResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string responderGlnField;
        
        private int numberOfHitsField;
        
        private int returnCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string responderGln {
            get {
                return this.responderGlnField;
            }
            set {
                this.responderGlnField = value;
            }
        }
        
        /// <remarks/>
        public int numberOfHits {
            get {
                return this.numberOfHitsField;
            }
            set {
                this.numberOfHitsField = value;
            }
        }
        
        /// <remarks/>
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GepirVersion2CompletedEventHandler(object sender, GepirVersion2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GepirVersion2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GepirVersion2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPartyByGLNCompletedEventHandler(object sender, GetPartyByGLNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartyByGLNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartyByGLNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirParty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirParty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOwnerOfGLNCompletedEventHandler(object sender, GetOwnerOfGLNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOwnerOfGLNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOwnerOfGLNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirParty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirParty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPartyByGTINCompletedEventHandler(object sender, GetPartyByGTINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartyByGTINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartyByGTINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirParty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirParty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPartyBySSCCCompletedEventHandler(object sender, GetPartyBySSCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartyBySSCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartyBySSCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirParty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirParty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPartyByNameCompletedEventHandler(object sender, GetPartyByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartyByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartyByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirParty Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirParty)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetItemByGTINCompletedEventHandler(object sender, GetItemByGTINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemByGTINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemByGTINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStatisticsCompletedEventHandler(object sender, GetStatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirStatistics Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAuthorizationCompletedEventHandler(object sender, GetAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gepirAuthorization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gepirAuthorization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SessionAuthorizeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591