//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Consumentor.ShopGun.Gateway.se.mediabanken.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductServiceSoap", Namespace="http://www.mediabanken.se/")]
    public partial class ProductService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback TestAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductListDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllAvailableEANsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChangedProductsEANsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductService() {
            this.Url = global::Consumentor.ShopGun.Gateway.Properties.Settings.Default.Consumentor_ShopGun_Gateway_se_mediabanken_www_ProductService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestAuthorizationCompletedEventHandler TestAuthorizationCompleted;
        
        /// <remarks/>
        public event GetProductDataCompletedEventHandler GetProductDataCompleted;
        
        /// <remarks/>
        public event GetProductListDataCompletedEventHandler GetProductListDataCompleted;
        
        /// <remarks/>
        public event GetAllAvailableEANsCompletedEventHandler GetAllAvailableEANsCompleted;
        
        /// <remarks/>
        public event GetChangedProductsEANsCompletedEventHandler GetChangedProductsEANsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mediabanken.se/TestAuthorization", RequestNamespace="http://www.mediabanken.se/", ResponseNamespace="http://www.mediabanken.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestAuthorization() {
            object[] results = this.Invoke("TestAuthorization", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAuthorizationAsync() {
            this.TestAuthorizationAsync(null);
        }
        
        /// <remarks/>
        public void TestAuthorizationAsync(object userState) {
            if ((this.TestAuthorizationOperationCompleted == null)) {
                this.TestAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestAuthorizationOperationCompleted);
            }
            this.InvokeAsync("TestAuthorization", new object[0], this.TestAuthorizationOperationCompleted, userState);
        }
        
        private void OnTestAuthorizationOperationCompleted(object arg) {
            if ((this.TestAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestAuthorizationCompleted(this, new TestAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mediabanken.se/GetProductData", RequestNamespace="http://www.mediabanken.se/", ResponseNamespace="http://www.mediabanken.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] GetProductData(string[] eanVec) {
            object[] results = this.Invoke("GetProductData", new object[] {
                        eanVec});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDataAsync(string[] eanVec) {
            this.GetProductDataAsync(eanVec, null);
        }
        
        /// <remarks/>
        public void GetProductDataAsync(string[] eanVec, object userState) {
            if ((this.GetProductDataOperationCompleted == null)) {
                this.GetProductDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDataOperationCompleted);
            }
            this.InvokeAsync("GetProductData", new object[] {
                        eanVec}, this.GetProductDataOperationCompleted, userState);
        }
        
        private void OnGetProductDataOperationCompleted(object arg) {
            if ((this.GetProductDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDataCompleted(this, new GetProductDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mediabanken.se/GetProductListData", RequestNamespace="http://www.mediabanken.se/", ResponseNamespace="http://www.mediabanken.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListProduct[] GetProductListData(string[] eanVec) {
            object[] results = this.Invoke("GetProductListData", new object[] {
                        eanVec});
            return ((ListProduct[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductListDataAsync(string[] eanVec) {
            this.GetProductListDataAsync(eanVec, null);
        }
        
        /// <remarks/>
        public void GetProductListDataAsync(string[] eanVec, object userState) {
            if ((this.GetProductListDataOperationCompleted == null)) {
                this.GetProductListDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductListDataOperationCompleted);
            }
            this.InvokeAsync("GetProductListData", new object[] {
                        eanVec}, this.GetProductListDataOperationCompleted, userState);
        }
        
        private void OnGetProductListDataOperationCompleted(object arg) {
            if ((this.GetProductListDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductListDataCompleted(this, new GetProductListDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mediabanken.se/GetAllAvailableEANs", RequestNamespace="http://www.mediabanken.se/", ResponseNamespace="http://www.mediabanken.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAllAvailableEANs() {
            object[] results = this.Invoke("GetAllAvailableEANs", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAvailableEANsAsync() {
            this.GetAllAvailableEANsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAvailableEANsAsync(object userState) {
            if ((this.GetAllAvailableEANsOperationCompleted == null)) {
                this.GetAllAvailableEANsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllAvailableEANsOperationCompleted);
            }
            this.InvokeAsync("GetAllAvailableEANs", new object[0], this.GetAllAvailableEANsOperationCompleted, userState);
        }
        
        private void OnGetAllAvailableEANsOperationCompleted(object arg) {
            if ((this.GetAllAvailableEANsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllAvailableEANsCompleted(this, new GetAllAvailableEANsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mediabanken.se/GetChangedProductsEANs", RequestNamespace="http://www.mediabanken.se/", ResponseNamespace="http://www.mediabanken.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetChangedProductsEANs(System.DateTime changedAfter) {
            object[] results = this.Invoke("GetChangedProductsEANs", new object[] {
                        changedAfter});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChangedProductsEANsAsync(System.DateTime changedAfter) {
            this.GetChangedProductsEANsAsync(changedAfter, null);
        }
        
        /// <remarks/>
        public void GetChangedProductsEANsAsync(System.DateTime changedAfter, object userState) {
            if ((this.GetChangedProductsEANsOperationCompleted == null)) {
                this.GetChangedProductsEANsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChangedProductsEANsOperationCompleted);
            }
            this.InvokeAsync("GetChangedProductsEANs", new object[] {
                        changedAfter}, this.GetChangedProductsEANsOperationCompleted, userState);
        }
        
        private void OnGetChangedProductsEANsOperationCompleted(object arg) {
            if ((this.GetChangedProductsEANsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChangedProductsEANsCompleted(this, new GetChangedProductsEANsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.mediabanken.se/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    public partial class AllergyInfo {
        
        private string substanceNameField;
        
        private ContainsAllergenic containsField;
        
        private string remarkField;
        
        /// <remarks/>
        public string SubstanceName {
            get {
                return this.substanceNameField;
            }
            set {
                this.substanceNameField = value;
            }
        }
        
        /// <remarks/>
        public ContainsAllergenic Contains {
            get {
                return this.containsField;
            }
            set {
                this.containsField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    public enum ContainsAllergenic {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Possible,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    public partial class MarkInfo {
        
        private int markIdField;
        
        private string markNameField;
        
        /// <remarks/>
        public int MarkId {
            get {
                return this.markIdField;
            }
            set {
                this.markIdField = value;
            }
        }
        
        /// <remarks/>
        public string MarkName {
            get {
                return this.markNameField;
            }
            set {
                this.markNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Product))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    public partial class ListProduct {
        
        private string eANField;
        
        private string imageURL_Jpg66pxField;
        
        private string imageURL_Jpg150pxField;
        
        private string imageURL_Jpg300pxField;
        
        private string supplierField;
        
        private string trademarkField;
        
        private string nameField;
        
        private string weightVolumeField;
        
        private MarkInfo[] markingsField;
        
        /// <remarks/>
        public string EAN {
            get {
                return this.eANField;
            }
            set {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL_Jpg66px {
            get {
                return this.imageURL_Jpg66pxField;
            }
            set {
                this.imageURL_Jpg66pxField = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL_Jpg150px {
            get {
                return this.imageURL_Jpg150pxField;
            }
            set {
                this.imageURL_Jpg150pxField = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL_Jpg300px {
            get {
                return this.imageURL_Jpg300pxField;
            }
            set {
                this.imageURL_Jpg300pxField = value;
            }
        }
        
        /// <remarks/>
        public string Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        public string Trademark {
            get {
                return this.trademarkField;
            }
            set {
                this.trademarkField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string WeightVolume {
            get {
                return this.weightVolumeField;
            }
            set {
                this.weightVolumeField = value;
            }
        }
        
        /// <remarks/>
        public MarkInfo[] Markings {
            get {
                return this.markingsField;
            }
            set {
                this.markingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/")]
    public partial class Product : ListProduct {
        
        private string categoryField;
        
        private string contentField;
        
        private string nutritionField;
        
        private string originField;
        
        private string storageField;
        
        private string durabilityField;
        
        private string suppArtNoField;
        
        private AllergyInfo[] allergiesField;
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string Nutrition {
            get {
                return this.nutritionField;
            }
            set {
                this.nutritionField = value;
            }
        }
        
        /// <remarks/>
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string Storage {
            get {
                return this.storageField;
            }
            set {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        public string Durability {
            get {
                return this.durabilityField;
            }
            set {
                this.durabilityField = value;
            }
        }
        
        /// <remarks/>
        public string SuppArtNo {
            get {
                return this.suppArtNoField;
            }
            set {
                this.suppArtNoField = value;
            }
        }
        
        /// <remarks/>
        public AllergyInfo[] Allergies {
            get {
                return this.allergiesField;
            }
            set {
                this.allergiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TestAuthorizationCompletedEventHandler(object sender, TestAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductDataCompletedEventHandler(object sender, GetProductDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductListDataCompletedEventHandler(object sender, GetProductListDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductListDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductListDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListProduct[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListProduct[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllAvailableEANsCompletedEventHandler(object sender, GetAllAvailableEANsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllAvailableEANsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllAvailableEANsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetChangedProductsEANsCompletedEventHandler(object sender, GetChangedProductsEANsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChangedProductsEANsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChangedProductsEANsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591