#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="gepirStatistics")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class gepirStatisticsGWO
    {
        
        /// <remarks/>
        private System.DateTime periodBegin;
        
        /// <remarks/>
        private System.DateTime periodEnd;
        
        /// <remarks/>
        private System.Collections.Generic.List<gepirStatisticsStatisticsLineGWO> statisticsLine;
        
        /// <remarks/>
        private decimal version;
        
        public gepirStatisticsGWO()
        {
            this.version = ((decimal)(3.10m));
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", ElementName="periodBegin")]
        public System.DateTime PeriodBegin
        {
            get
            {
                return this.periodBegin;
            }
            set
            {
                if ((this.periodBegin != value))
                {
                    this.periodBegin = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", ElementName="periodEnd")]
        public System.DateTime PeriodEnd
        {
            get
            {
                return this.periodEnd;
            }
            set
            {
                if ((this.periodEnd != value))
                {
                    this.periodEnd = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("statisticsLine")]
        public System.Collections.Generic.List<gepirStatisticsStatisticsLineGWO> StatisticsLine
        {
            get
            {
                return this.statisticsLine;
            }
            set
            {
                if ((this.statisticsLine != value))
                {
                    this.statisticsLine = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="version")]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.10")]
        public decimal Version
        {
            get
            {
                return this.version;
            }
            set
            {
                if ((this.version != value))
                {
                    this.version = value;
                }
            }
        }
    }
}
