#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="gepirResponseHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gepir.org/", IsNullable=false, ElementName="gepirResponseHeader")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class gepirResponseHeaderGWO : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <remarks/>
        private string responderGln;
        
        /// <remarks/>
        private int numberOfHits;
        
        /// <remarks/>
        private int returnCode;
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr;
        
        public gepirResponseHeaderGWO()
        {
        }
        
        public gepirResponseHeaderGWO(string responderGln, int numberOfHits, int returnCode, System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr)
        {
            this.responderGln = responderGln;
            this.numberOfHits = numberOfHits;
            this.returnCode = returnCode;
            this.anyAttr = anyAttr;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="responderGln")]
        public string ResponderGln
        {
            get
            {
                return this.responderGln;
            }
            set
            {
                if ((this.responderGln != value))
                {
                    this.responderGln = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="numberOfHits")]
        public int NumberOfHits
        {
            get
            {
                return this.numberOfHits;
            }
            set
            {
                if ((this.numberOfHits != value))
                {
                    this.numberOfHits = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="returnCode")]
        public int ReturnCode
        {
            get
            {
                return this.returnCode;
            }
            set
            {
                if ((this.returnCode != value))
                {
                    this.returnCode = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.Generic.List<System.Xml.XmlAttribute> AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                if ((this.anyAttr != value))
                {
                    this.anyAttr = value;
                }
            }
        }
    }
}
