#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="gepirRequestHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gepir.org/", IsNullable=false, ElementName="gepirRequestHeader")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class gepirRequestHeaderGWO : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <remarks/>
        private string requesterGln;
        
        /// <remarks/>
        private int cascade;
        
        /// <remarks/>
        private bool cascadeSpecified;
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr;
        
        public gepirRequestHeaderGWO()
        {
        }
        
        public gepirRequestHeaderGWO(string requesterGln, int cascade, bool cascadeSpecified, System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr)
        {
            this.requesterGln = requesterGln;
            this.cascade = cascade;
            this.cascadeSpecified = cascadeSpecified;
            this.anyAttr = anyAttr;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="requesterGln")]
        public string RequesterGln
        {
            get
            {
                return this.requesterGln;
            }
            set
            {
                if ((this.requesterGln != value))
                {
                    this.requesterGln = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="cascade")]
        public int Cascade
        {
            get
            {
                return this.cascade;
            }
            set
            {
                if ((this.cascade != value))
                {
                    this.cascade = value;
                    this.cascadeSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CascadeSpecified
        {
            get
            {
                return this.cascadeSpecified;
            }
            set
            {
                if ((this.cascadeSpecified != value))
                {
                    this.cascadeSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.Generic.List<System.Xml.XmlAttribute> AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                if ((this.anyAttr != value))
                {
                    this.anyAttr = value;
                }
            }
        }
    }
}
