#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    public interface IProductSearchWebServiceGateway : Consumentor.ShopGun.Gateway.IWebServiceSettings
    {
        
        gepirPartyGWO GetPartyByGLN(GetPartyByGLNGWO getPartyByGLN1);
        
        gepirPartyGWO GetOwnerOfGLN(GetOwnerOfGLNGWO getOwnerOfGLN1);
        
        gepirPartyGWO GetPartyByGTIN(GetPartyByGTINGWO getPartyByGTIN1);
        
        gepirPartyGWO GetPartyBySSCC(GetPartyBySSCCGWO getPartyBySSCC1);
        
        gepirPartyGWO GetPartyByName(GetPartyByNameGWO getPartyByName1);
        
        gepirItemGWO GetItemByGTIN(GetItemByGTINGWO getItemByGTIN1);
        
        gepirStatisticsGWO GetStatistics(GetStatisticsGWO getStatistics1);
        
        System.Xml.XmlNode gepir00();
    }
}
