#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="itemDataLineTypeTradeItemUnitDescriptor")]
    public enum itemDataLineTypeTradeItemUnitDescriptor
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BASE_UNIT_OR_EACH")]
        BASE_UNIT_OR_EACH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PACK_OR_INNER_PACK")]
        PACK_OR_INNER_PACK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CASE")]
        CASE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DISPLAY_SHIPPER")]
        DISPLAY_SHIPPER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PALLET")]
        PALLET,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MIXED_MODULE")]
        MIXED_MODULE,
    }
}
