#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="itemDataLineTypeChildItemsChildItem")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class itemDataLineTypeChildItemsChildItemGWO
    {
        
        /// <remarks/>
        private string gtin;
        
        /// <remarks/>
        private string numberContained;
        
        public itemDataLineTypeChildItemsChildItemGWO()
        {
        }
        
        public itemDataLineTypeChildItemsChildItemGWO(string gtin, string numberContained)
        {
            this.gtin = gtin;
            this.numberContained = numberContained;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="gtin")]
        public string Gtin
        {
            get
            {
                return this.gtin;
            }
            set
            {
                if ((this.gtin != value))
                {
                    this.gtin = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", ElementName="numberContained")]
        public string NumberContained
        {
            get
            {
                return this.numberContained;
            }
            set
            {
                if ((this.numberContained != value))
                {
                    this.numberContained = value;
                }
            }
        }
    }
}
