#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="partyRoleListType")]
    public enum partyRoleListType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BILL_TO")]
        BILL_TO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BUYER")]
        BUYER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CONSUMER")]
        CONSUMER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CORPORATE_IDENTITY")]
        CORPORATE_IDENTITY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DELIVERY_PARTY")]
        DELIVERY_PARTY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DISTRIBUTOR_AND_OR_BROKER")]
        DISTRIBUTOR_AND_OR_BROKER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="INFORMATION_PROVIDER")]
        INFORMATION_PROVIDER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="INVOICEE")]
        INVOICEE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ISSUER_OF_INVOICE")]
        ISSUER_OF_INVOICE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LOGISTICS_SERVICE_PROVIDER")]
        LOGISTICS_SERVICE_PROVIDER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MANUFACTURING_PLANT")]
        MANUFACTURING_PLANT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MARK_FOR")]
        MARK_FOR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MESSAGE_FROM")]
        MESSAGE_FROM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MESSAGE_RECIPIENT")]
        MESSAGE_RECIPIENT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OPERATOR")]
        OPERATOR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PARTY_TO_RECEIVE_COMMERCIAL_INVOICE")]
        PARTY_TO_RECEIVE_COMMERCIAL_INVOICE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PAYEE")]
        PAYEE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PAYER")]
        PAYER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SELLER")]
        SELLER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SHIP_FROM")]
        SHIP_FROM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SHIP_TO")]
        SHIP_TO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="STORE")]
        STORE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SUPPLIER")]
        SUPPLIER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WAREHOUSE_AND_OR_DEPOT")]
        WAREHOUSE_AND_OR_DEPOT,
    }
}
