#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Gepir
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gepir.org/", TypeName="partyChildType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class partyChildTypeGWO
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<partyRoleListType> partyChildRole;
        
        /// <remarks/>
        private string gln;
        
        public partyChildTypeGWO()
        {
        }
        
        public partyChildTypeGWO(System.Collections.Generic.List<partyRoleListType> partyChildRole, string gln)
        {
            this.partyChildRole = partyChildRole;
            this.gln = gln;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("partyChildRole")]
        public System.Collections.Generic.List<partyRoleListType> PartyChildRole
        {
            get
            {
                return this.partyChildRole;
            }
            set
            {
                if ((this.partyChildRole != value))
                {
                    this.partyChildRole = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="gln")]
        public string Gln
        {
            get
            {
                return this.gln;
            }
            set
            {
                if ((this.gln != value))
                {
                    this.gln = value;
                }
            }
        }
    }
}
