#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Server
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://consumentor.com/ShopGunDomain", TypeName="Product")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ProductGWO
    {
        
        /// <remarks/>
        private BrandGWO brand;
        
        /// <remarks/>
        private string globalTradeItemNumber;
        
        /// <remarks/>
        private System.DateTime lastUpdated;
        
        /// <remarks/>
        private bool lastUpdatedSpecified;
        
        /// <remarks/>
        private string productName;
        
        /// <remarks/>
        private System.Nullable<int> quantity;
        
        /// <remarks/>
        private bool quantitySpecified;
        
        /// <remarks/>
        private string quantityUnit;
        
        public ProductGWO()
        {
        }
        
        public ProductGWO(BrandGWO brand, string globalTradeItemNumber, System.DateTime lastUpdated, bool lastUpdatedSpecified, string productName, System.Nullable<int> quantity, bool quantitySpecified, string quantityUnit)
        {
            this.brand = brand;
            this.globalTradeItemNumber = globalTradeItemNumber;
            this.lastUpdated = lastUpdated;
            this.lastUpdatedSpecified = lastUpdatedSpecified;
            this.productName = productName;
            this.quantity = quantity;
            this.quantitySpecified = quantitySpecified;
            this.quantityUnit = quantityUnit;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="Brand")]
        public BrandGWO Brand
        {
            get
            {
                return this.brand;
            }
            set
            {
                if ((this.brand != value))
                {
                    this.brand = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="GlobalTradeItemNumber")]
        public string GlobalTradeItemNumber
        {
            get
            {
                return this.globalTradeItemNumber;
            }
            set
            {
                if ((this.globalTradeItemNumber != value))
                {
                    this.globalTradeItemNumber = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="LastUpdated")]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.lastUpdated;
            }
            set
            {
                if ((this.lastUpdated != value))
                {
                    this.lastUpdated = value;
                    this.lastUpdatedSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdatedSpecified
        {
            get
            {
                return this.lastUpdatedSpecified;
            }
            set
            {
                if ((this.lastUpdatedSpecified != value))
                {
                    this.lastUpdatedSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="ProductName")]
        public string ProductName
        {
            get
            {
                return this.productName;
            }
            set
            {
                if ((this.productName != value))
                {
                    this.productName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="Quantity")]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.quantity;
            }
            set
            {
                if ((this.quantity != value))
                {
                    this.quantity = value;
                    this.quantitySpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantitySpecified;
            }
            set
            {
                if ((this.quantitySpecified != value))
                {
                    this.quantitySpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="QuantityUnit")]
        public string QuantityUnit
        {
            get
            {
                return this.quantityUnit;
            }
            set
            {
                if ((this.quantityUnit != value))
                {
                    this.quantityUnit = value;
                }
            }
        }
    }
}
