#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Server
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IProductSearchContract", Namespace="http://consumentor.com/ShopGunDomain")]
    public partial class ProductSearchWebServiceGateway : Consumentor.ShopGun.Gateway.WebServiceBase, IProductSearchWebServiceGateway
    {
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        /// <remarks/>
        public ProductSearchWebServiceGateway()
        {
            
        }
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://consumentor.com/ShopGunDomain/IProductSearchContract/Search", RequestNamespace="http://consumentor.com/ShopGunDomain", ResponseNamespace="http://consumentor.com/ShopGunDomain", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProductGWO Search([System.Xml.Serialization.XmlElementAttribute(IsNullable=true, ElementName="globalTradeItemNumber")] string globalTradeItemNumber)
        {
            object[] results = this.Invoke("Search", new object[] {
                        globalTradeItemNumber});
            return ((ProductGWO)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string globalTradeItemNumber)
        {
            this.SearchAsync(globalTradeItemNumber, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string globalTradeItemNumber, object userState)
        {
            if ((this.SearchOperationCompleted == null))
            {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        globalTradeItemNumber}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg)
        {
            if ((this.SearchCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgsGWO(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }
}
