#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Opv
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/", TypeName="AuthHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.mediabanken.se/", IsNullable=false, ElementName="AuthHeader")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class AuthHeaderGWO : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <remarks/>
        private string username;
        
        /// <remarks/>
        private string password;
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr;
        
        public AuthHeaderGWO()
        {
        }
        
        public AuthHeaderGWO(string username, string password, System.Collections.Generic.List<System.Xml.XmlAttribute> anyAttr)
        {
            this.username = username;
            this.password = password;
            this.anyAttr = anyAttr;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="username")]
        public string Username
        {
            get
            {
                return this.username;
            }
            set
            {
                if ((this.username != value))
                {
                    this.username = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="password")]
        public string Password
        {
            get
            {
                return this.password;
            }
            set
            {
                if ((this.password != value))
                {
                    this.password = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Collections.Generic.List<System.Xml.XmlAttribute> AnyAttr
        {
            get
            {
                return this.anyAttr;
            }
            set
            {
                if ((this.anyAttr != value))
                {
                    this.anyAttr = value;
                }
            }
        }
    }
}
