#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Opv
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/", TypeName="ContainsAllergenic")]
    public enum ContainsAllergenic
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="No")]
        No,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Possible")]
        Possible,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Yes")]
        Yes,
    }
}
