#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Opv
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductGWO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/", TypeName="ListProduct")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ListProductGWO
    {
        
        /// <remarks/>
        private string eAN;
        
        /// <remarks/>
        private string imageURL_Jpg66px;
        
        /// <remarks/>
        private string imageURL_Jpg150px;
        
        /// <remarks/>
        private string imageURL_Jpg300px;
        
        /// <remarks/>
        private string supplier;
        
        /// <remarks/>
        private string trademark;
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string weightVolume;
        
        /// <remarks/>
        private System.Collections.Generic.List<MarkInfoGWO> markings;
        
        public ListProductGWO()
        {
        }
        
        public ListProductGWO(string eAN, string imageURL_Jpg66px, string imageURL_Jpg150px, string imageURL_Jpg300px, string supplier, string trademark, string name, string weightVolume, System.Collections.Generic.List<MarkInfoGWO> markings)
        {
            this.eAN = eAN;
            this.imageURL_Jpg66px = imageURL_Jpg66px;
            this.imageURL_Jpg150px = imageURL_Jpg150px;
            this.imageURL_Jpg300px = imageURL_Jpg300px;
            this.supplier = supplier;
            this.trademark = trademark;
            this.name = name;
            this.weightVolume = weightVolume;
            this.markings = markings;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EAN")]
        public string EAN
        {
            get
            {
                return this.eAN;
            }
            set
            {
                if ((this.eAN != value))
                {
                    this.eAN = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ImageURL_Jpg66px")]
        public string ImageURL_Jpg66px
        {
            get
            {
                return this.imageURL_Jpg66px;
            }
            set
            {
                if ((this.imageURL_Jpg66px != value))
                {
                    this.imageURL_Jpg66px = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ImageURL_Jpg150px")]
        public string ImageURL_Jpg150px
        {
            get
            {
                return this.imageURL_Jpg150px;
            }
            set
            {
                if ((this.imageURL_Jpg150px != value))
                {
                    this.imageURL_Jpg150px = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ImageURL_Jpg300px")]
        public string ImageURL_Jpg300px
        {
            get
            {
                return this.imageURL_Jpg300px;
            }
            set
            {
                if ((this.imageURL_Jpg300px != value))
                {
                    this.imageURL_Jpg300px = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Supplier")]
        public string Supplier
        {
            get
            {
                return this.supplier;
            }
            set
            {
                if ((this.supplier != value))
                {
                    this.supplier = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Trademark")]
        public string Trademark
        {
            get
            {
                return this.trademark;
            }
            set
            {
                if ((this.trademark != value))
                {
                    this.trademark = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="WeightVolume")]
        public string WeightVolume
        {
            get
            {
                return this.weightVolume;
            }
            set
            {
                if ((this.weightVolume != value))
                {
                    this.weightVolume = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Markings")]
        public System.Collections.Generic.List<MarkInfoGWO> Markings
        {
            get
            {
                return this.markings;
            }
            set
            {
                if ((this.markings != value))
                {
                    this.markings = value;
                }
            }
        }
    }
}
