#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Opv
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/", TypeName="MarkInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MarkInfoGWO
    {
        
        /// <remarks/>
        private int markId;
        
        /// <remarks/>
        private string markName;
        
        public MarkInfoGWO()
        {
        }
        
        public MarkInfoGWO(int markId, string markName)
        {
            this.markId = markId;
            this.markName = markName;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MarkId")]
        public int MarkId
        {
            get
            {
                return this.markId;
            }
            set
            {
                if ((this.markId != value))
                {
                    this.markId = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MarkName")]
        public string MarkName
        {
            get
            {
                return this.markName;
            }
            set
            {
                if ((this.markName != value))
                {
                    this.markName = value;
                }
            }
        }
    }
}
