#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// data objects suffixed with GWO 
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Consumentor.ShopGun.Gateway.Opv
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wscf", "0.7.6319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mediabanken.se/", TypeName="Product")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class ProductGWO : ListProductGWO
    {
        
        /// <remarks/>
        private string category;
        
        /// <remarks/>
        private string content;
        
        /// <remarks/>
        private string nutrition;
        
        /// <remarks/>
        private string origin;
        
        /// <remarks/>
        private string storage;
        
        /// <remarks/>
        private string durability;
        
        /// <remarks/>
        private string suppArtNo;
        
        /// <remarks/>
        private System.Collections.Generic.List<AllergyInfoGWO> allergies;
        
        public ProductGWO()
        {
        }
        
        public ProductGWO(string category, string content, string nutrition, string origin, string storage, string durability, string suppArtNo, System.Collections.Generic.List<AllergyInfoGWO> allergies)
        {
            this.category = category;
            this.content = content;
            this.nutrition = nutrition;
            this.origin = origin;
            this.storage = storage;
            this.durability = durability;
            this.suppArtNo = suppArtNo;
            this.allergies = allergies;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Category")]
        public string Category
        {
            get
            {
                return this.category;
            }
            set
            {
                if ((this.category != value))
                {
                    this.category = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Content")]
        public string Content
        {
            get
            {
                return this.content;
            }
            set
            {
                if ((this.content != value))
                {
                    this.content = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Nutrition")]
        public string Nutrition
        {
            get
            {
                return this.nutrition;
            }
            set
            {
                if ((this.nutrition != value))
                {
                    this.nutrition = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Origin")]
        public string Origin
        {
            get
            {
                return this.origin;
            }
            set
            {
                if ((this.origin != value))
                {
                    this.origin = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Storage")]
        public string Storage
        {
            get
            {
                return this.storage;
            }
            set
            {
                if ((this.storage != value))
                {
                    this.storage = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Durability")]
        public string Durability
        {
            get
            {
                return this.durability;
            }
            set
            {
                if ((this.durability != value))
                {
                    this.durability = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SuppArtNo")]
        public string SuppArtNo
        {
            get
            {
                return this.suppArtNo;
            }
            set
            {
                if ((this.suppArtNo != value))
                {
                    this.suppArtNo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Allergies")]
        public System.Collections.Generic.List<AllergyInfoGWO> Allergies
        {
            get
            {
                return this.allergies;
            }
            set
            {
                if ((this.allergies != value))
                {
                    this.allergies = value;
                }
            }
        }
    }
}
